server:
  port: 8021
  
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
   # url: jdbc:mysql://localhost:3306/untact?serverTimezone=Asia/Seoul&characterEncoding=UTF-8  
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/untact?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull    
    username: spring
    password: spring
    
mybatis:
  type-aliases-package:  com.sbs.untact.dto